management:
  server:
    port: 9002
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator/admin
  endpoint:
    health:
      show-components: always
      show-details: always
info:
  app:
    name: Mushrooms Application
    description: up- and download your mushrooms with their geolocation
    version: snapshot 1.0
spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    pool:
      enabled: true
      initial-size: 50
      max-size: 100
      max-idle-time: 30
    url: r2dbc:postgresql://postgres@localhost:5432/
    username: postgres
    password: P@ssw0rd
logging:
  level:
    org:
      springframework:
        r2dbc=DEBUG:

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081